export default {
    FETCH_PREPARATIONS: 'FETCH_PREPARATIONS',
    RECEIVE_PREPARATIONS: 'RECEIVE_PREPARATIONS',
    RECEIVE_PREPARATION: 'RECEIVE_PREPARATION',
    RECEIVE_NOT_FINISHED_PREPARATIONS: 'RECEIVE_NOT_FINISHED_PREPARATIONS',
    DELETE_PREPARATION: 'DELETE_PREPARATION',
}
