export default {
    FETCH_NOTIFICATIONS: 'FETCH_NOTIFICATIONS',
    RECEIVE_NOTIFICATIONS: 'RECEIVE_NOTIFICATIONS',
    RECEIVE_NOTIFICATION: 'RECEIVE_NOTIFICATION',
    DELETE_NOTIFICATION: 'DELETE_NOTIFICATION',
}
