export default {
    FETCH_BUSINESSES: 'FETCH_BUSINESSES',
    RECEIVE_BUSINESSES: 'RECEIVE_BUSINESSES',
    RECEIVE_BUSINESS: 'RECEIVE_BUSINESS',
    DELETE_BUSINESS: 'DELETE_BUSINESS',
    RECEIVE_BUSINESS_NEXT_REFERENCE: 'RECEIVE_BUSINESS_NEXT_REFERENCE',

    // States
    WAITING: 'waiting',
    COSTING: 'costing',
    PROGRESS: 'progress',
    CLOSED: 'closed',
    ARCHIVED: 'archived',
}
