export default {
    FETCH_USERS: 'FETCH_USERS',
    RECEIVE_USERS: 'RECEIVE_USERS',
    RECEIVE_USER: 'RECEIVE_USER',
    RECEIVE_USER_SUBORDONATES: 'RECEIVE_USER_SUBORDONATES',
    DELETE_USER: 'DELETE_USER',

    // Roles
    ADD_USER_ROLE: 'ADD_USER_ROLE',
    REMOVE_USER_ROLE: 'REMOVE_USER_ROLE',

    // Passwords
    RESET_PASSWORD: 'RESET_PASSWORD'
}
